python build_parent_sample_worker.py 911 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_911.log
python build_parent_sample_worker.py 910 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_910.log
python build_parent_sample_worker.py 920 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_920.log
python build_parent_sample_worker.py 933 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_933.log
python build_parent_sample_worker.py 922 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_922.log
python build_parent_sample_worker.py 932 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_932.log
python build_parent_sample_worker.py 934 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_934.log
python build_parent_sample_worker.py 944 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_944.log
python build_parent_sample_worker.py 940 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_940.log
python build_parent_sample_worker.py 935 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_935.log
python build_parent_sample_worker.py 923 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_923.log
python build_parent_sample_worker.py 921 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_921.log
python build_parent_sample_worker.py 926 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_926.log
python build_parent_sample_worker.py 941 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_941.log
python build_parent_sample_worker.py 946 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_946.log
python build_parent_sample_worker.py 945 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_945.log
python build_parent_sample_worker.py 948 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_948.log
python build_parent_sample_worker.py 947 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_947.log
python build_parent_sample_worker.py 952 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_952.log
python build_parent_sample_worker.py 924 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_924.log
python build_parent_sample_worker.py 950 --kepler_catalog_path /mnt/ceph/users/polymathic/Kepler/all_lcs_catalog_cache.txt &> healpix_950.log
