#!/bin/bash
#SBATCH --qos=regular
#SBATCH --nodes=1
#SBATCH --constraint=cpu
#SBATCH --time=10:00:00
#SBATCH --array=0-3
#SBATCH -A m4474

echo $SLURM_ARRAY_TASK_ID

module load python

srun python build_parent_sample.py /global/cfs/cdirs/cosmo/data/legacysurvey /pscratch/sd/f/flanusse/decals_export --catalog_only --only_catalog_id $SLURM_ARRAY_TASK_ID

srun python build_parent_sample.py /global/cfs/cdirs/cosmo/data/legacysurvey /pscratch/sd/f/flanusse/decals_export --only_catalog_id $SLURM_ARRAY_TASK_ID